#version: '3.8'
services:
  db:
    image: mysql:8.0.37
    #restart: always
    environment:
      #MYSQL_ROOT_HOST: "%"
      #MYSQL_USER: admin
      #MYSQL_PASSWORD: 123
      #MYSQL_ROOT_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: systouch_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    #restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    depends_on:
      - db
volumes:
  db_data:



  #version: '3.8'
#services:
#  mysqldev:
#    image: mysql:8.0.31
#    volumes:
#      - db_data:/var/lib/mysql
#    ports:
#      - 3307:3307
#    environment:
#      MYSQL_ROOT_HOST: "%"
#      #MYSQL_ROOT_PASSWORD: adm!@#12
#      MYSQL_DATABASE: systouch_db
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mysqldev
#      PMA_PORT: 3307
#      #MYSQL_ROOT_PASSWORD: adm!@#123
#    ports:
#      - 8081:80
#    depends_on:
#      - mysqldev
#
#volumes:
#  db_data:



  # https://www.youtube.com/watch?v=nDst-CRKt_k&ab_channel=Build%26Run

  #docker exec -it 08a26dacf884 ping [hostname_mysql]
